# Generated by Django 3.1.1 on 2020-12-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.IntegerField(default=1, verbose_name='Document ID')),
                ('cosine_score', models.FloatField(default=1.0, verbose_name='Cosine Score')),
            ],
        ),
    ]
